### PR TITLE
Feature/fix annotations updating before testrun is done

### LINKED ISSUE #212: After starting Intellij RunTImeException occurs
**Describe the bug**
When I start Intellij IDEA in our git repo locally I get the following exception:
```
java.lang.RuntimeException: No visit() method implemented for class: org.codehaus.groovy.ast.ClassNode
	at org.codehaus.groovy.ast.ASTNode.visit(ASTNode.java:52)
	at com.amos.pitmutationmate.pitmutationmate.services.PluginCheckerService.checkGroovyBuildFile(PluginCheckerService.kt:151)
	at com.amos.pitmutationmate.pitmutationmate.services.PluginCheckerService.checkPlugins(PluginCheckerService.kt:50)
	at com.amos.pitmutationmate.pitmutationmate.activity.LaunchActivity.execute$lambda$2$lambda$0(LaunchActivity.kt:25)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:209)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:22)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:191)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:843)
	at com.intellij.openapi.application.impl.ApplicationImpl$4.run(ApplicationImpl.java:463)
	at com.intellij.openapi.application.impl.RwLockHolder.runWithEnabledImplicitRead(RwLockHolder.kt:75)
	at com.intellij.openapi.application.impl.RwLockHolder.runWithImplicitRead(RwLockHolder.kt:67)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWithImplicitRead(ApplicationImpl.java:1436)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:82)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:124)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:44)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:792)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:733)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:761)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:695)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$12(IdeEventQueue.kt:589)
	at com.intellij.openapi.application.impl.RwLockHolder.runWithoutImplicitRead(RwLockHolder.kt:44)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:589)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:72)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:355)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:354)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:793)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:354)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:349)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:1014)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:106)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:1014)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$7(IdeEventQueue.kt:349)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:848)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:391)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```

**To Reproduce**
Install our plugin in IntelliJ IDEA through marketplace (don't use the runIDE task). Then close Intellij IDEA and restart it in the directory of our amos proj.

**Desktop (please complete the following information):**

- OS: Windows 11
- Version 2023.3.3

### PR DESCRIPTION
**Pull request by lheimbs**
I noticed sometimes the annotations don't update after a run.
This moves the annotation handling into the process handler.
I also moved the handler into it's own class to be able to test it and makes the run archiver a service.
Additionally 2485ba0e6e76d50ec1efb10aef34e2da7f92474e fixes #212

### CODE REVIEW

File: pitmutationmate/src/main/kotlin/com/amos/pitmutationmate/pitmutationmate/execution/ExecutionDoneProcessListener.kt [hunk 1]
```diff
@@ -0,0 +1,73 @@
...
+            restartCodeHighlighting()
+        }
+        // archive the pitest run
+        project.service<RunArchiveService>().archiveRun()
+    }
+
+    private fun restartCodeHighlighting() {
+        PluginState.isAnnotatorEnabled = true
+        val analyser = DaemonCodeAnalyzer.getInstance(project)
+        // moved tool window update since if it's done pitest didn't run through
```
Comment (nikomall34) [inline pitmutationmate/src/main/kotlin/com/amos/pitmutationmate/pitmutationmate/execution/ExecutionDoneProcessListener.kt:55]: What do you mean by this comment here?

File: pitmutationmate/src/main/kotlin/com/amos/pitmutationmate/pitmutationmate/execution/ExecutionDoneProcessListener.kt [hunk 2]
```diff
@@ -0,0 +1,73 @@
...
+        val psiFiles = classFqdns!!.split(",").map { getPsiFileFromFQN(project, it) }
+        psiFiles.forEach { file ->
+            if (file != null) {
+                analyser.restart(file)
```
Comment (nikomall34) [inline pitmutationmate/src/main/kotlin/com/amos/pitmutationmate/pitmutationmate/execution/ExecutionDoneProcessListener.kt:59]: And here, you're ensuring that the CodeAnalyzer is only run on the files that were tested by Pitest, right? So, the CodeAnalyzer no longer runs on the entire project? But couldn't this be slower because now you're searching the whole project multiple times if there are multiple classes in the Pitest run?

File: pitmutationmate/src/main/kotlin/com/amos/pitmutationmate/pitmutationmate/services/PluginCheckerService.kt [hunk 3]
```diff
@@ -148,7 +148,9 @@ class PluginCheckerService(private val project: Project) {
         )
         val groovyChecker = PluginCheckerGroovy()
         for (node in nodes) {
-            node.visit(groovyChecker)
+            if (node::class.java.declaredMethods.any { it.name == "visit" }) {
+                node.visit(groovyChecker)
+            }
```
Comment (nikomall34) [inline pitmutationmate/src/main/kotlin/com/amos/pitmutationmate/pitmutationmate/services/PluginCheckerService.kt:153]: With this we can close bug #212

**Review by nikomall34 — COMMENTED** [review]
I really like the refactoring and the test class! I just left some comments to make sure if I understood your changes correctly.

File: pitmutationmate/src/main/kotlin/com/amos/pitmutationmate/pitmutationmate/execution/ExecutionDoneProcessListener.kt (hunk 2 above)
Comment (lheimbs) [reply pitmutationmate/src/main/kotlin/com/amos/pitmutationmate/pitmutationmate/execution/ExecutionDoneProcessListener.kt:59]: Hmm could be that JavaPsiFacade.findClass takes a few ms more but as we have it now, every time the annotator runs, the mutation result service also parses the xmls so cutting down the number of annotator runs should reduce overall computing time.
And since the psi information is indexed, I dont think the search takes too long...

Comment (nikomall34) [reply pitmutationmate/src/main/kotlin/com/amos/pitmutationmate/pitmutationmate/execution/ExecutionDoneProcessListener.kt:58]: Ok, that makes sense. But shouldn't we consider changing this in general, with the XML parsing being executed every time we need the results? Do you think this would be possible, at least in the annotator?

**Review by nikomall34 — APPROVED** [review]

File: pitmutationmate/src/main/kotlin/com/amos/pitmutationmate/pitmutationmate/execution/ExecutionDoneProcessListener.kt (hunk 2 above)
Comment (lheimbs) [reply pitmutationmate/src/main/kotlin/com/amos/pitmutationmate/pitmutationmate/execution/ExecutionDoneProcessListener.kt:58]: Definitely! I've already started working on that but didn't want to put more in this PR
