### PR TITLE
Bugfix/224 all kinds of fixes

### LINKED ISSUE #213: Slow operations are prohibited on EDT
**Describe the bug**
When ever I test the plugin through runIDE task or when I download it I noticed this on the command line:
```
java.lang.Throwable: Slow operations are prohibited on EDT. See SlowOperations.assertSlowOperationsAreAllowed javadoc.
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:376)
	at com.intellij.util.SlowOperations.assertSlowOperationsAreAllowed(SlowOperations.java:101)
	at com.intellij.workspaceModel.core.fileIndex.impl.WorkspaceFileIndexDataImpl.ensureIsUpToDate(WorkspaceFileIndexDataImpl.kt:130)
	at com.intellij.workspaceModel.core.fileIndex.impl.WorkspaceFileIndexDataImpl.getFileInfo(WorkspaceFileIndexDataImpl.kt:75)
	at com.intellij.workspaceModel.core.fileIndex.impl.WorkspaceFileIndexImpl.getFileInfo(WorkspaceFileIndexImpl.kt:247)
	at com.intellij.openapi.roots.impl.ProjectFileIndexImpl.isUnderIgnored(ProjectFileIndexImpl.java:73)
	at com.intellij.openapi.roots.impl.ProjectFileIndexFacade.isUnderIgnored(ProjectFileIndexFacade.java:71)
	at com.intellij.psi.impl.file.impl.FileManagerImpl.isExcludedOrIgnored(FileManagerImpl.java:419)
	at com.intellij.psi.impl.file.impl.FileManagerImpl.findDirectoryImpl(FileManagerImpl.java:405)
	at com.intellij.psi.impl.file.impl.FileManagerImpl.findDirectory(FileManagerImpl.java:398)
	at com.intellij.psi.impl.PsiManagerImpl.findDirectory(PsiManagerImpl.java:175)
	at com.intellij.psi.AbstractFileViewProvider.shouldCreatePsi(AbstractFileViewProvider.java:89)
	at com.intellij.psi.SingleRootFileViewProvider.createFile(SingleRootFileViewProvider.java:144)
	at com.intellij.psi.SingleRootFileViewProvider.getPsiInner(SingleRootFileViewProvider.java:101)
	at com.intellij.psi.AbstractFileViewProvider.getPsi(AbstractFileViewProvider.java:185)
	at com.intellij.psi.impl.file.impl.FileManagerImpl.findFile(FileManagerImpl.java:360)
	at com.intellij.psi.impl.PsiManagerImpl.findFile(PsiManagerImpl.java:163)
	at com.amos.pitmutationmate.pitmutationmate.services.PluginCheckerService.checkKotlinBuildFile(PluginCheckerService.kt:128)
	at com.amos.pitmutationmate.pitmutationmate.services.PluginCheckerService.checkPlugins(PluginCheckerService.kt:44)
	at com.amos.pitmutationmate.pitmutationmate.activity.LaunchActivity.execute$lambda$2$lambda$0(LaunchActivity.kt:25)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:209)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:22)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:191)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:843)
	at com.intellij.openapi.application.impl.ApplicationImpl$4.run(ApplicationImpl.java:463)
	at com.intellij.openapi.application.impl.RwLockHolder.runWithEnabledImplicitRead(RwLockHolder.kt:75)
	at com.intellij.openapi.application.impl.RwLockHolder.runWithImplicitRead(RwLockHolder.kt:67)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWithImplicitRead(ApplicationImpl.java:1430)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:82)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:124)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:44)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:792)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:733)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:761)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:695)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$12(IdeEventQueue.kt:589)
	at com.intellij.openapi.application.impl.RwLockHolder.runWithoutImplicitRead(RwLockHolder.kt:44)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:589)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:72)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:355)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:354)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:793)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:354)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:349)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:1014)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:106)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:1014)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$7(IdeEventQueue.kt:349)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:848)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:391)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```

**To Reproduce**
Just test the plugin through runIDE or download it in the marketplace.

**Desktop (please complete the following information):**

- OS: Windows 11
- Version 2023.3.3

### PR DESCRIPTION
**Pull request by lheimbs**
Soooooooo...

this is a lot.
I'm sorry.

We'll have to see if we really want to accept this right before the final release.
Might also have to merge this afterwards.

### Companion plugin

1. add task to check for the other plugins

### Intellij plugin

1. PluginCheck: Check first if new task is available and then the task is executed before running a pitest task and the tasks output tells us if the pitest plugin is loaded.
2. PluginCheck: Checks are only ever run when executing pitest. No other times.
3. PluginCheck: Also error info is show in the tool window but other than that there is only a small tooltip when an error is detected. No disabling anything anymore.
4. Removed all file listener and file parsing shenanigans
5. Gradle can give us test folders when an intellij idea is used so added that to the testenv checker
6. Fixed a bug where right click on the gutter icon caused an exception
7. Slightly adjusted the annotations (IP wanted less intrusive killed display)
8. Cleaned up the tool window factory.
9. Allow users to add gradle cli options in settings. Also shows what is selected in settings better.

---

This fixes #213 #224 #228 and also most of the issues found by the IP.

### CODE REVIEW

File: pitmutationmate/src/main/kotlin/com/amos/pitmutationmate/pitmutationmate/configuration/SettingsEditor.kt [hunk 1]
```diff
@@ -21,19 +23,17 @@ class SettingsEditor : SettingsEditor<RunConfiguration>() {
     private val gradleTaskField: TextFieldWithHistory = TextFieldWithHistory()
     private val gradleExecutableField: TextFieldWithBrowseButton = TextFieldWithBrowseButton()
     private val targetClasses: JBTextField = JBTextField()
-    private val buildTypesField: JBTextField = JBTextField()
+    private val buildTypesField: TextFieldWithHistory = TextFieldWithHistory()
     private val verboseCheckbox = JCheckBox("Enable Pitest verbose mode")
```
Comment (nikomall34) [inline pitmutationmate/src/main/kotlin/com/amos/pitmutationmate/pitmutationmate/configuration/SettingsEditor.kt:27]:
```suggestion
    private val verboseCheckbox = JBCheckBox("Enable Pitest verbose mode")
```

File: pitmutationmate/src/main/kotlin/com/amos/pitmutationmate/pitmutationmate/configuration/SettingsEditor.kt [hunk 2]
```diff
@@ -66,11 +66,23 @@ class SettingsEditor : SettingsEditor<RunConfiguration>() {
...
+            gradleTaskField.setTextAndAddToHistory("pitest")
+        }
         targetClasses.text = runConfiguration.classFQN
-        gradleTaskField.text = runConfiguration.taskName
-        runConfiguration.gradleExecutable.also { gradleExecutableField.text = it ?: "" }
         buildTypesField.text = runConfiguration.buildType
         verboseCheckbox.isSelected = runConfiguration.verbose
+
+        runConfiguration.project.service<PluginCheckerService>().getBuildTypes().forEach { buildType ->
+            buildTypesField.history.add(buildType)
```
Comment (nikomall34) [inline pitmutationmate/src/main/kotlin/com/amos/pitmutationmate/pitmutationmate/configuration/SettingsEditor.kt:84]: Did you test this here with the history. Because for me it didn't work. Btw how did you trigger a reset?

File: pitmutationmate/src/main/kotlin/com/amos/pitmutationmate/pitmutationmate/services/PluginCheckerService.kt [hunk 3]
```diff
@@ -3,200 +3,237 @@
...
+        } else {
+            ""
         }
     }
 
-    private class PluginsAvailability {
-        var pitestPluginAvailable: Boolean = false
-        var companionPluginAvailable: Boolean = false
+    private fun getPitestPluginName(): List<String> {
+        val isAndroid = pluginCheckData?.androidPitestPluginApplied ?: false
```
Comment (nikomall34) [inline pitmutationmate/src/main/kotlin/com/amos/pitmutationmate/pitmutationmate/services/PluginCheckerService.kt:189]:
```suggestion
        val isAndroid = pluginCheckData?.androidPluginApplied ?: false
```

**Review by nikomall34 — APPROVED** [review]
TWo things that I noticed are that the HistoryTab is not getting updated and the when we pitest for many classes. So the Text in targetClasses JBTextField is very large you cannot resize the window anymore. This is because of the Layout that the FormBuilder uses I guess. I am currently working on these issues and I think we shouldn't put them in this PR so you can merge it.

File: pitmutationmate/src/main/kotlin/com/amos/pitmutationmate/pitmutationmate/services/PluginCheckerService.kt (hunk 3 above)
Comment (lheimbs) [reply pitmutationmate/src/main/kotlin/com/amos/pitmutationmate/pitmutationmate/services/PluginCheckerService.kt]: I have applied that in 6a6e78808240e870197b75531f527903bdff2f82
I also added some more doc string in the pluginchecker in an effort to make things clearer
